### ISSUE TITLE
melodic release

### ISSUE THREAD

**Issue by rhaschke** [shadow-robot/ethercat_grant#3]
Please can you release this package into Melodic?

**Comment by AndriyPt** [comment]
Hey @rhaschke we are in the process of releasing this package

**Comment by AndriyPt** [comment]
@rhaschke added to ROS Melodic automatic build. Here you could find status of the package http://repositories.ros.org/status_page/ros_melodic_default.html?q=ethercat_grant . I guess we need to wait till next ROS Melodic update to get new package. Please let me know in case if you have any issues in ROS Melodic with it. Thanks.
