### ISSUE TITLE
rpath problems in melodic

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/ethercat_grant#4]
In bionic/melodic, as user, I roslaunch _sr_ethercat_hand_config_ sr_rhand.launch  which internally call a rosrun of the _ros_ethercat_loop_  prefixed with _ethercat_grant_

I get a _librosconsole_bridge_ not found, although it is installed.

if I ldd ros_ethercat_loop as user, it finds the lib, but not as root as root, it does not finds the lib

What we tested : 

* added a run dependency to rosconsole_bridge in package.xml of ros_ethercat_loop => nothing changes
* added it as build dependency + a findpackage of rosconsole_bridge => did not work
* it seems to be a bew RUN_PATH/RPATH problem mentioned here  https://stackoverflow.com/questions/47117443/dynamic-linking-with-rpath-not-working-under-ubuntu-17-10

So we tried the solution they suggest, directly in _ros_ethercat_loop_, and add this flag `-Wl,--disable-new-dtags`

* BIONIC without this new flag 
```
readelf -d ros_ethercat_loop 
     0x000000000000001d (RUNPATH)            Library runpath: [/vol/famula/bionic/lib:/vol/famula/bionic/ros/melodic/lib:/vol/famula/bionic/ros/melodic/lib:/opt/ros/melodic/lib]

LD_DEBUG=libs ldd ros_ethercat_loop | grep rosconsole_bridge -A 5
   find library=librosconsole_bridge.so [0]; searching
    search path=/vol/famula/bionic/lib        (RUNPATH from file ./ros_ethercat_loop)
      trying file=/vol/famula/bionic/lib/librosconsole_bridge.so
   search cache=/etc/ld.so.cache
   search path=(.....)/usr/lib/x86_64:/usr/lib        (system search path)
```
* BIONIC with this new flag (the RUNPATH is now RPATH again), but still not found
```
readelf -d ros_ethercat_loop 
 0x000000000000000f (RPATH)              Library rpath: [/vol/famula/bionic/ros/melodic/lib:/opt/ros/melodic/lib:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::]

LD_DEBUG=libs ldd ros_ethercat_loop | grep rosconsole_bridge -A 5
    find library=librosconsole_bridge.so [0]; searching
     search path=/vol/famula/bionic/lib        (RPATH from file ./ros_ethercat_loop)
       trying file=/vol/famula/bionic/lib/librosconsole_bridge.so
     search cache=/etc/ld.so.cache
     search path=(....)/usr/lib/x86_64:/usr/lib        (system search path)
```

* XENIAL works nice
```
readelf -d ros_ethercat_loop
   0x000000000000000f (RPATH)              Library rpath: [/vol/famula/nightly/lib:/vol/famula/nightly/ros/kinetic/lib:/opt/ros/kinetic/lib]

LD_DEBUG=libs ldd ros_ethercat_loop | grep rosconsole_bridge -A 5
   find library=librosconsole_bridge.so [0]; searching
    search path=/vol/famula/nightly/lib        (RPATH from file ./ros_ethercat_loop)
     trying file=/vol/famula/nightly/lib/librosconsole_bridge.so
    search path=/vol/famula/nightly/lib:/vol/famula/nightly/ros/kinetic/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu        (RPATH from file ./ros_ethercat_loop)
     trying file=/vol/famula/nightly/lib/librosconsole_bridge.so
     trying file=/vol/famula/nightly/ros/kinetic/lib/librosconsole_bridge.so
     trying file=/opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib/librosconsole_bridge.so
     trying file=/opt/ros/kinetic/lib/librosconsole_bridge.so
```

So dependent libraries are not deployed in a consistent way yet to use the RUNPATH or backward-compatible RPATH (like libros-*-urdf)

@rhaschke has an idea how to solve this, and we will test it on our side. Please hold on a few days, until we provide a PR.

**Comment by guihomework** [comment]
Our solution was initially to "enforce" the user LD_LIBRARY_PATH to be passed to the called ros_ethercat_loop from within the ethercat_grant code. Unfortunately the user LD_LIBRARY_PATH is not accessible anymore since the SETUID explicitly ignores/drops it already for ethercat_grant.

Here's a snippet from the ld.so manpage:
```
       The  necessary  shared libraries needed by the program are
       searched for in the following order : 
(...)
      o  Using the environment  variable  LD_LIBRARY_PATH  (unless  the  exe‐
          cutable is being run in secure-execution mode; see below).  in which
          case it is ignored.

```
To circumvent that, one could pass some info from command line arguments to ethercat_grant, such as LD_LIBRARY_PATH, and then use the execve() function to pass this again as environment variable.

But I am not an expert, and I am not sure if these lines https://github.com/shadow-robot/ethercat_grant/blob/kinetic-devel/src/ethercat_grant.cpp#L58 reduce the priviledges enough to safely pass "any" LD_LIBRARY_PATH content to the ros_ethercat_loop.

**Comment by guihomework** [comment]
Follow-up, after implementing an arg passing of the LD_LIBRARY_PATH to the env for the child process,  indeed the drop of privileges are apparently not sufficient or maybe will just never work.
See my question there
https://stackoverflow.com/questions/53818499/ld-library-path-in-envp-arg-of-execve-gets-removed-even-if-the-calling-setuid

**Comment by guihomework** [comment]
I wonder if @robwheeler would be kind to share his point of view and/or ideas as the initial creator of pr2_grant ?

**Comment by guihomework** [comment]
Well, things are not looking good for our workaround according to this https://stackoverflow.com/a/53835603/10801865

setting capabilities **also** triggers the "secure environment" and so LD_LIBRARY_PATH gets removed from environment of the "granted" file.

**Comment by guihomework** [comment]
FYI, we won't continue finding a solution for this issue, we will probably have the realtime loop be owned by root or so until there is a solution found.

**Comment by AndriyPt** [comment]
Thank you @guihomework for keeping us updated. 
I have added it to our TODO list during ROS Melodic migration. But I guess for now it is not our highest priority.

**Comment by guihomework** [comment]
The patch was included in the ethercat loop now, so closing here because there is no solution in this package.
