### ISSUE TITLE
Noetic release?

### ISSUE THREAD

**Issue by Olavhaasie** [shadow-robot/ethercat_grant#6]
Hi there, are you planning on creating a release for ROS Noetic?

**Comment by garaemon** [comment]
Hi, I want to use ethercat_grant on ROS Noetic too. 
Could you release ethercat_grant as apt package for ROS Noetic?

**Comment by beatrizleon** [comment]
Thanks for your messages. We are planning to transition to Noetic at the beginning of the next year.

**Comment by BasVolkers** [comment]
Any update on this ?

**Comment by biofotis** [comment]
> Any update on this ?

Yes we made the release it just needs time to get into debian. Once its there I will close this issue

**Comment by furushchev** [comment]
Hello, I use `ethercat_grant` on noetic installed using `apt-get install ros-noetic-ethercat-grant` and it looks `chmod +s` is not applied to the program, which causes Permission denied error on launching ethercat controller node.
Could you check the release procedure to noetic?

```
ls -lFah /opt/ros/noetic/ethercat_grant
-rwxr-xr-x 1 root root 15K  May  5 04:28 ethercat_grant*                                                                
```

**Comment by biofotis** [comment]
We released it and it was fine before but the latest one had the script missing. We made a new release today so hopefully the problems will be sorted on it gets into debians again.

**Comment by biofotis** [comment]
the release is available now so I am closing this issue
